theme: jekyll-theme-modernist
title: EviBas: An Evidence-Based Worldview
description: Scientific knowledge is poorly disseminated by academics and politicians alike. This is but a meager attempt at addressing common misconceptions.
